### ISSUE TITLE
Support Property Substitution

### ISSUE THREAD

**Issue by hfhbd** [cashapp/licensee#168]
https://maven.apache.org/ref/3.5.4/maven-model/maven.html
According to the properties section, any value can be substituted with a property. See https://repo1.maven.org/maven2/one/util/streamex/0.8.1/streamex-0.8.1.pom for a pom file.

**Comment by JakeWharton** [comment]
I knew this was a possibility but hoped it never would manifest in practice. Ugh.

**Comment by hfhbd** [comment]
I didn't know maven does not replace the values during upload but keeps the variables in the POM file . But on the other hand, this is a rare use-case and you could apply the workaround allowing it manually.

**Comment by JakeWharton** [comment]
Yeah it's because you could pull a newer parent pom which defines a property for the child and need to see the new value.

**Comment by JakeWharton** [comment]
In the past I've used Maven as a library to do things the Maven way. And to no surprise it looks like we can use its model to load the pom hierarchy and (presumably) get the effective pom.

https://stackoverflow.com/a/4881362/132047

**Comment by JakeWharton** [comment]
I'm on paternity leave until April. If someone else wants to attempt this I would welcome it. Otherwise I'll do it sometime after I get back.
