### ISSUE TITLE
License check fails with 1.7.0

### ISSUE THREAD

**Issue by emartynov** [cashapp/licensee#180]
Hi people,

Our project license check fails if we use 1.7 plugin version and pass with 1.6:

```
> Error while evaluating property 'coordinatesToPomInfo' of task ':project:licenseeDebug'.
   > Failed to calculate the value of task ':project:licenseeDebug' property 'coordinatesToPomInfo'.
      > 1 problem was encountered while building the effective model for com.google.code.gson:gson:2.8.9
        [ERROR] Failed to determine Java version for profile doclint-java8-disable @ com.google.code.gson:gson-parent:2.8.9
```

**Comment by emartynov** [comment]
We have it as transitive from:
* com.auth0.android:jwtdecode:2.0.2
* androidx.security:security-crypto:1.1.0-alpha05

You can add it to your test project to reproduce the issue.

**Comment by zsperske** [comment]
I also ran into a similar issue:

```
Error while evaluating property 'coordinatesToPomInfo' of task ':app:licenseeInternalDebug'.
   > Failed to calculate the value of task ':app:licenseeInternalDebug' property 'coordinatesToPomInfo'.
      > 3 problems were encountered while building the effective model for org.joda:joda-money:1.0.1
        [ERROR] Failed to determine Java version for profile java6and7 @ org.joda:joda-parent:1.3.1
        [ERROR] Failed to determine Java version for profile java6and7and8 @ org.joda:joda-parent:1.3.1
        [ERROR] Failed to determine Java version for profile java9plus @ org.joda:joda-parent:1.3.1
```

**Comment by rohilchodankar** [comment]
We are also using 1.7 due to the support for configuration cache. With the latest changes, we are seeing the following error.
This issue most likely is related

```Configuration cache state could not be cached: field `__coordinatesToPomInfo__` of task `:module:licenseeRelease` of type `app.cash.licensee.LicenseeTask`: error writing value of type 'org.gradle.api.internal.provider.DefaultMapProperty'```

**Comment by bddckr** [comment]
@hfhbd If you could look at this, it would be much appreciated - it seems like [your recently merged configuration cache work](https://github.com/cashapp/licensee/pull/141) is potentially related to this issue.

**Comment by bddckr** [comment]
I've downgraded back to version 1.6.0 and added this for the time being:
```kotlin
tasks
    .matching { it.name.contains("licensee") }
    .configureEach {
        notCompatibleWithConfigurationCache(
            "https://github.com/cashapp/licensee/issues/180"
        )
    }
```

With this, the build won't fail, but the cache won't be set either (I won't set `configuration-cache-problems` to `warn`):
> Configuration cache problems found in the task will be reported but won't cause the build to fail.
>
> The presence of incompatible tasks in the task graph will cause the configuration state to be discarded at the end of the build unless the global `configuration-cache-problems` option is set to `warn`, in which case the configuration state would still be cached in a best-effort manner as usual for the option.
>
> https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#notCompatibleWithConfigurationCache-java.lang.String-

**Comment by hfhbd** [comment]
I don't think your build fails due to the CC change, this was a long time ago. Instead, my PR introducing the new maven parser causes your build to fail for some reason. Will take a look coming days.
