### ISSUE TITLE
Allowed SPDX identifier 'GPL 2' is unused

### ISSUE THREAD

**Issue by Goooler** [cashapp/licensee#221]
Licensee 1.7.0:

```groovy
licensee {
    allow("Apache-2.0")
    allow("BSD-3-Clause")
    allow("GPL 2")
    allowUrl("https://api.github.com/licenses/apache-2.0")
    allowUrl("https://api.github.com/licenses/bsd-3-clause")
    allowUrl("https://github.com/patrykmichalik/opto/blob/master/LICENSE")
    allowUrl("https://github.com/RikkaApps/HiddenApiRefinePlugin/blob/main/LICENSE")
}
```

Generated artifacts.json:
```json
[
    {
        "groupId": "me.xdrop",
        "artifactId": "fuzzywuzzy",
        "version": "1.4.0",
        "name": "fuzzywuzzy",
        "unknownLicenses": [
            {
                "name": "GPL 2",
                "url": "https://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
            }
        ],
        "scm": {
            "url": "https://github.com/xdrop/fuzzywuzzy"
        }
    },
]
```

- Pom: https://repo1.maven.org/maven2/me/xdrop/fuzzywuzzy/1.4.0/fuzzywuzzy-1.4.0.pom
- Repro: https://github.com/LawnchairLauncher/lawnchair/pull/3531

**Comment by JakeWharton** [comment]
"GPL 2" is not a valid SPDX identifier. We don't match licenses against names. The URLs are mapped to SPDX identifiers, and failing that you can allow the URL.

It sounds like we have a bug where we are not rejecting invalid SPDX identifiers. This would cause your build to fail for using an invalid one, and then you would be forced to allow the URL. And, optionally, to submit that URL as a fallback URL to the project mapped to the `GPL-2.0-only` or `GPL-2.0-or-later` SPDX identifiers.
