### ISSUE TITLE
Add Android Studio license to list of recognized licenses

### ISSUE THREAD

**Issue by IsakTheHacker** [cashapp/licensee#276]
I get this error when applying the plugin to my Wear OS project:
```
com.google.android.gms:play-services-base:18.0.1
 - ERROR: Unknown license URL 'https://developer.android.com/studio/terms.html' is NOT allowed
com.google.android.gms:play-services-basement:18.0.0
 - ERROR: Unknown license URL 'https://developer.android.com/studio/terms.html' is NOT allowed
com.google.android.gms:play-services-tasks:18.0.1
 - ERROR: Unknown license URL 'https://developer.android.com/studio/terms.html' is NOT allowed
com.google.android.gms:play-services-wearable:18.1.0
 - ERROR: Unknown license URL 'https://developer.android.com/studio/terms.html' is NOT allowed
```

In future versions, maybe this license url should be added to the list of recognized licenses

**Comment by JakeWharton** [comment]
This plugin uses the SPDX license database for its license identifiers which only contains open source licenses. A proprietary license like Google's will not be on the list. You can add the URL as being allowed to your config if you accept its terms. There's no way for us to recognize the URL as a license as it doesn't map to any SPDX identifier.
