### ISSUE TITLE
Exclude `platform`/`enforcedPlatform` dependencies

### ISSUE THREAD

**Issue by mateuszkwiecinski** [cashapp/licensee#310]
Library maintainers sometimes publish BOM artifacts, which are meant to be loaded as a `platfrom`/`enforcedPlatform` dependency, for example
``` groovy
dependencies {
    implementation(platform("androidx.compose:compose-bom:2024.03.00"))
}
```
with the latest 1.9.1 version, the `bom` dependency is listed within tool output:
```kotlin
    Artifact(
      groupId = "androidx.compose",
      artifactId = "compose-bom",
      version = "2024.03.00",
      name = "Jetpack Compose Libraries BOM",
      spdxLicenses = listOf(
        SpdxLicense(
          identifier = "Apache-2.0",
          name = "Apache License 2.0",
          url = "https://www.apache.org/licenses/LICENSE-2.0",
        ),
      ),
      scm = null,
      unknownLicenses = emptyList(),
    ),
```

From my understanding `platform`/`enforcedPlatform` dependencies are only used to determine version constraints and are not really included in the output artifacts (hence its License/Notice doesn't have to be attachec?)

The only workaround I was able to figure out was to iterate over every `bom` dependency and call `ignoreDependencies`, but maybe there could be an option to autmatically exclude all `platform`/`enforcedPlatform` dependencies? 

For more context, Gradle's `dependencies` task indicates platform dependencies via `(c)` marker, described as:
>(c) - A dependency constraint, not a dependency. The dependency affected by the constraint occurs elsewhere in the tree.

**Comment by JakeWharton** [comment]
We can probably ignore any dependency with a packaging pom.

**Comment by mateuszkwiecinski** [comment]
That was quick 🚀 I confirm 1.10.0 works in an expected way - I stopped seeing BOMs listed in the tool output. Thank you 🙇

**Comment by hfhbd** [comment]
The most time I spend with was debugging `AttributeContainer.getAttributw` always returning `null` for the existing typed `Attribute` until I found this issue questioning the design of typed attributes in general: https://github.com/gradle/gradle/issues/8854
