### ISSUE TITLE
Support allowing by license name

### ISSUE THREAD

**Issue by eygraber** [cashapp/licensee#374]
Several POMs specify the license name using the SPDX License Name field, e.g. [Apollo Kotlin](https://github.com/apollographql/apollo-kotlin/blob/main/gradle.properties#L10) uses `MIT License`.

It would be nice to be able to allow that, which is more palatable than `allowUrl("https://raw.githubusercontent.com/apollographql/apollo-kotlin/main/LICENSE")`.

**Comment by JakeWharton** [comment]
Duplicate of #137
