### ISSUE TITLE
License for com.russhwolf:multiplatform-settings:0.8 can't be retrieved

### ISSUE THREAD

**Issue by vanniktech** [cashapp/licensee#50]
When using:

```
sourceSets.commonMain.dependencies {
  api "com.russhwolf:multiplatform-settings:0.8.0"
}
```

I'm getting:

```
com.russhwolf:multiplatform-settings:0.8
 - ERROR: Artifact declares no licenses!
```

Looking at the [POM](https://search.maven.org/artifact/com.russhwolf/multiplatform-settings/0.8/jar) it's present. 

I'm applying the module to my app, while the API is declared in a shared KMP module.

**Comment by vanniktech** [comment]
Same is true for kotlinx-serialization-core-iosx64: https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlinx-serialization-core-iosx64/1.2.2/klib

**Comment by JakeWharton** [comment]
Probably #30 or related

**Comment by JakeWharton** [comment]
Confirmed it's the same.
