### ISSUE TITLE
Classify the repository with topics

### ISSUE THREAD

**Issue by aivantsov** [cashapp/licensee#76]
Consider classifying your repository with the following topics:
-  `gradle-plugin` 
- `license-management` 
- `license-checking`
- `license-system`

See also [Classifying your repository with topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics).

**Comment by JakeWharton** [comment]
Generally, I don't do this on any repository I work on. I don't get value out of them and I find them visually unappealing.
