### ISSUE TITLE
Support Android dynamic feature modules

### ISSUE THREAD

**Issue by sb-software** [cashapp/licensee#83]
As far as I can tell the plugin doesn't currently work for dynamic feature modules used in Android applications. It would be a nice thing to have as dynamic features is becoming more and more common, at least in larger Android projects. Perhaps it would be possible from the application module to detect `android.dynamicFeatures` dependencies and traverse into them to find additional third-parties to check?

**Comment by JakeWharton** [comment]
I'm not sure about your claims about them becoming common, but yes supporting them is likely trivial.

**Comment by JakeWharton** [comment]
This is blocked on AGP 7.3 being stable for https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/variant/Component#runtimeConfiguration().
